######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 16 23:49:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chip8_cpu.hpp chip8_system.hpp emu_window.hpp
SOURCES += chip8_cpu.cpp chip8_system.cpp emu_window.cpp main.cpp
